### ISSUE TITLE
onSignal tests for order

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop-test#1]
`onSignal` is specified that the driver MAY choose the order. However, we have a test that tests the order.

[Test Case](https://github.com/async-interop/event-loop-test/blob/3755a3c9e9f5bddd1362a4bbdb3a5c20da30bb12/src/Test.php#L573-L610) – [Specification](https://github.com/async-interop/event-loop/blob/master/src/Loop.php#L236)

**Comment by bwoebi** [comment]
Good point. Before async-interop/event-loop#80 that test was correct.

Now these signals can all occur at the same time, only important fact is that the defer() is executed first.
