### ISSUE TITLE
Tag releases related to event loop package version.

### ISSUE THREAD

**Issue by ghost** [async-interop/event-loop-test#2]
It would be very helpful if you started tagging releases for the loop test package that are aligned with releases of the loop API package. I was running into dependency version problems because dev-master of the test package requires ^0.4|dev-master now and i require version ^0.3 of the loop API in my package.

I don't want to change the loop version requirement to dev-master because i am using minimum-stability stable and prefer to rely on a stable version of the API.

**Comment by bwoebi** [comment]
Oh, let me tag a 0.3 version for the previous commit.

**Comment by bwoebi** [comment]
Done, now you can require ^0.3 for this package.
